package frontend.Lexer;

// 枚举类
public enum LexType {
    MINU, MULT, MOD, SEMICN, COMMA, LPARENT, RPARENT, LBRACK, RBRACK, LBRACE, RBRACE, ERROR, NOT, NEQ, LEQ, LSS, GEQ, GRE, EQL, ASSIGN, OR, AND, PLUS

}